In [17]:
import numpy as np
from numpy.random import randint
import scipy.optimize

# Removed random right-hand side values and changed nomenclature a bit.
def f(x):
    x1, x2, x3, x4 = x
    return np.asarray((x1*x2,x1*x3,x1*x4,x2*x3,x2*x4,x3*x4))

# The second parameter is used to set the solution vector using the args
# argument of leastsq.
def system(x,b):
    return (f(x)-b)

b = np.array([2,3,4,6,8,12])
# this b array should end up giving x1, x2, x3, x4 = 1, 2, 3, 4
x = scipy.optimize.leastsq(system, np.asarray((2,2,2,2)), args=b)[0]

In [31]:
test = [0.344641,0.42078699,0.75974698, 0.50802347, 0.55354871, 0.48954548]
print(test)

[0.344641, 0.42078699, 0.75974698, 0.50802347, 0.55354871, 0.48954548]


In [33]:
import numpy as np
from numpy.random import randint
import scipy.optimize

# Removed random right-hand side values and changed nomenclature a bit.
def f(x):
    x1, x2, x3, x4 = x
    return np.asarray((x1*x2,x1*x3,x1*x4,x2*x3,x2*x4,x3*x4))

# The second parameter is used to set the solution vector using the args
# argument of leastsq.
def system(x,b):
    return (f(x)-b)

b = test#np.array([2,3,4,6,8,12])
# this b array should end up giving x1, x2, x3, x4 = 1, 2, 3, 4
x = scipy.optimize.leastsq(system, np.asarray((2,2,2,2)), args=b)[0]
print(x)

[0.72940063 0.60663532 0.60376139 0.93750455]


In [34]:
test_extra = [0.344641, 0.344641,  0.42078699, 0.75974698, 0.50802347, 0.55354871, 0.48954548]

import numpy as np
from numpy.random import randint
import scipy.optimize

# Removed random right-hand side values and changed nomenclature a bit.
def f(x):
    x1, x2, x3, x4 = x
    return np.asarray((x1*x2,x1*x2,x1*x3,x1*x4,x2*x3,x2*x4,x3*x4))

# The second parameter is used to set the solution vector using the args
# argument of leastsq.
def system(x,b):
    return (f(x)-b)

b = test_extra#np.array([2,3,4,6,8,12])
# this b array should end up giving x1, x2, x3, x4 = 1, 2, 3, 4
x = scipy.optimize.leastsq(system, np.asarray((2,2,2,2)), args=b)[0]
print(x)

[0.70557874 0.58009127 0.6040317  0.96136476]


In [37]:
test_2 = [np.sqrt(2)*0.344641, 0.42078699, 0.75974698, 0.50802347, 0.55354871, 0.48954548]
print(test_2)

[0.48739597634982584, 0.42078699, 0.75974698, 0.50802347, 0.55354871, 0.48954548]


In [38]:
import numpy as np
from numpy.random import randint
import scipy.optimize

# Removed random right-hand side values and changed nomenclature a bit.
def f(x):
    x1, x2, x3, x4 = x
    return np.asarray((np.sqrt(2)*x1*x2,x1*x3,x1*x4,x2*x3,x2*x4,x3*x4))

# The second parameter is used to set the solution vector using the args
# argument of leastsq.
def system(x,b):
    return (f(x)-b)

b = test_2#np.array([2,3,4,6,8,12])
# this b array should end up giving x1, x2, x3, x4 = 1, 2, 3, 4
x = scipy.optimize.leastsq(system, np.asarray((2,2,2,2)), args=b)[0]
print(x)

[0.70557874 0.58009127 0.6040317  0.96136476]


test 1.5 and test 2 are equivalent!

In [25]:
a = 100
b = 150
c = 200
d = 175

arg_array = [a*b, a*c, a*d, b*c, b*d, c*d]
print(arg_array)

[15000, 20000, 17500, 30000, 26250, 35000]


In [26]:
import numpy as np
from numpy.random import randint
import scipy.optimize

# Removed random right-hand side values and changed nomenclature a bit.
def f(x):
    x1, x2, x3, x4 = x
    return np.asarray((x1*x2,x1*x3,x1*x4,x2*x3,x2*x4,x3*x4))

# The second parameter is used to set the solution vector using the args
# argument of leastsq.
def system(x,b):
    return (f(x)-b)

#b = np.array([2,3,4,6,8,12])
# this b array should end up giving x1, x2, x3, x4 = 1, 2, 3, 4
x = scipy.optimize.leastsq(system, np.asarray((100,100,100,100)), args=arg_array)[0]
print(x)

[100. 150. 200. 175.]


In [27]:
a = 100
b = 150
c = 200
d = 175

arg_array = [a*b, a*c, a*d, b*c, b*d, c*d]
print(arg_array)
noise = np.random.normal(0,0.05,6)
noise[0] = 0
noisy_arg_array = []
for i in range(0, len(arg_array)):
    noisy_data = (1-noise[i])*arg_array[i]
    noisy_arg_array.append(noisy_data)
print(noise)
print(noisy_arg_array)

[15000, 20000, 17500, 30000, 26250, 35000]
[ 0.         -0.10522227 -0.0622748   0.07046616 -0.0084087   0.06071947]
[15000.0, 22104.445375825748, 18589.808963610954, 27886.01531470827, 26470.728337048666, 32874.818661604695]


In [28]:
import numpy as np
from numpy.random import randint
import scipy.optimize

# Removed random right-hand side values and changed nomenclature a bit.
def f(x):
    x1, x2, x3, x4 = x
    return np.asarray((x1*x2,x1*x3,x1*x4,x2*x3,x2*x4,x3*x4))

# The second parameter is used to set the solution vector using the args
# argument of leastsq.
def system(x,b):
    return (f(x)-b)

#b = np.array([2,3,4,6,8,12])
# this b array should end up giving x1, x2, x3, x4 = 1, 2, 3, 4
x = scipy.optimize.leastsq(system, np.asarray((100,100,100,100)), args=noisy_arg_array)[0]
print(x)
print(x[0]*x[1])

[109.20714957 146.76382729 191.86060293 173.92016862]
16027.659238625458


In [29]:
noisy_arg_array_2 = noisy_arg_array.copy()
noisy_arg_array_2[0] = np.sqrt(100)*noisy_arg_array_2[0]

In [30]:

import numpy as np
from numpy.random import randint
import scipy.optimize

# Removed random right-hand side values and changed nomenclature a bit.
def f(x):
    x1, x2, x3, x4 = x
    return np.asarray((np.sqrt(100)*x1*x2,x1*x3,x1*x4,x2*x3,x2*x4,x3*x4))

# The second parameter is used to set the solution vector using the args
# argument of leastsq.
def system(x,b):
    return (f(x)-b)

#b = np.array([2,3,4,6,8,12])
# this b array should end up giving x1, x2, x3, x4 = 1, 2, 3, 4
x = scipy.optimize.leastsq(system, np.asarray((110,100,100,100)), args=noisy_arg_array_2)[0]
print(x)
print(x[0]*x[1])

[105.02736634 143.0639638  194.06285611 175.23859375]
15025.631336847347


In [31]:
noisy_arg_array_3 = noisy_arg_array.copy()
noisy_arg_array_3[0] = np.sqrt(1000)*noisy_arg_array_3[0]

In [32]:
import numpy as np
from numpy.random import randint
import scipy.optimize

# Removed random right-hand side values and changed nomenclature a bit.
def f(x):
    x1, x2, x3, x4 = x
    return np.asarray((np.sqrt(1000)*x1*x2,x1*x3,x1*x4,x2*x3,x2*x4,x3*x4))

# The second parameter is used to set the solution vector using the args
# argument of leastsq.
def system(x,b):
    return (f(x)-b)

#b = np.array([2,3,4,6,8,12])
# this b array should end up giving x1, x2, x3, x4 = 1, 2, 3, 4
x = scipy.optimize.leastsq(system, np.asarray((100,100,100,100)), args=noisy_arg_array_3)[0]
print(x)
print(x[0]*x[1])

[104.92911093 142.97844657 194.113741   175.26787435]
15002.601279895864


going to try and recreate what I am doing above but with a weight array in the system definition!

In [24]:
import numpy as np
from numpy.random import randint
import scipy.optimize

# Removed random right-hand side values and changed nomenclature a bit.
def f(x):
    x1, x2, x3, x4 = x
    return np.asarray((x1*x2,x1*x3,x1*x4,x2*x3,x2*x4,x3*x4))

# The second parameter is used to set the solution vector using the args
# argument of leastsq.
def system(x,w,b):
    return w*(f(x)-b)


weights = [np.sqrt(1000),1,1,1,1,1]
#b = np.array([2,3,4,6,8,12])
# this b array should end up giving x1, x2, x3, x4 = 1, 2, 3, 4
x = scipy.optimize.leastsq(system, np.asarray((100,100,100,100)), args=(weights,noisy_arg_array))[0]
print(x)
print(x[0]*x[1])

[ 97.81625095 153.35262334 194.24182335 170.02819452]
15000.378687696137


The above weights the equation and the corresponding b value!

In [9]:
noisy_arg_array_3

[474341.64902525686,
 19193.801704937046,
 16751.67534609302,
 29854.58029084083,
 26215.485580927612,
 32854.5899758518]